name: CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs: 
    
    build:
        runs-on: ubuntu-latest
        
        steps: 
        - uses: actions/checkout@v4
        - name: Login DockerHub
          env: 
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

          run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
       
        - name: Push to DockerHub
          # uses: docker/build-push-action@v2
          # with:
          #   context: .
          #   push: true
          #   tags: steeve05/my-node-app:latest
          run: |
               sudo docker build -t my-node-app .
               docker push steeve05/my-node-app:tagname


        - name: Set up SSH agent
          uses: webfactory/ssh-agent@v0.5.3
          with:
              ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
    
        - name: Deploy to EC2
          run: |
              ssh -o StrictHostKeyChecking=no ubuntu@ec2-52-55-52-46 << 'EOF'
              docker pull steeve05/my-node-app:latest
              docker run -d -p 3000:3000 --name my-node-app steeve05/my-node-app:latest
              EOF