name: CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs: 
    
    build:
        runs-on: ubuntu-latest
        
        steps: 
          
        - name: Checkout
        - uses: actions/checkout@v4
       
        - name: Login DockerHub
        - uses: docker/login-action@v3
          env: 
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}

       
        - name: Push to DockerHub
          run: |
            docker build -t steeve05/my-node-app:latest .
            docker push steeve05/my-node-app:latest
          

 

        # - name: Set up SSH agent
        #   uses: webfactory/ssh-agent@v0.5.3
        #   with:
        #       ssh-private-key: {{ secrets.EC2_SSH_KEY }}
    
        # - name: Deploy to EC2
        #   run: |
        #       ssh -o StrictHostKeyChecking=no ubuntu@ec2-52-55-52-46 << 'EOF'
        #       docker pull steeve05/my-node-app:latest
        #       docker run -d -p 3000:3000 --name my-node-app steeve05/my-node-app:latest
        #       EOF